# Workflow name
name: Check App
permissions:
  contents: read

# When it will be triggered
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Where it will run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-android
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_ALIAS: ${{ secrets.SIGNING_ALIAS }}

      - name: Create debug build
        run: ./gradlew app:assembleDebug

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: debug apk
          path: app/build/outputs/apk/debug/*

  checks:
    name: Check - ${{ matrix.task }}
    strategy:
      fail-fast: false
      matrix:
        task: [ test, lint, spotlessCheck, detekt ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-android
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_ALIAS: ${{ secrets.SIGNING_ALIAS }}

      - name: Run ${{ matrix.task }}
        run: ./gradlew ${{ matrix.task }}

      - name: Upload ${{ matrix.task }} reports
        uses: actions/upload-artifact@v7
        with:
          name: reports-${{ matrix.task }}
          path: ./**/build/reports
        if: always()

  sonar:
    needs: [ checks ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-android
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_ALIAS: ${{ secrets.SIGNING_ALIAS }}

      - name: Cache SonarQube packages
        uses: actions/cache@v6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Download check reports
        uses: actions/download-artifact@v7
        with:
          pattern: reports-*
          merge-multiple: true
          path: .

      - name: Perform SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar

      - name: Upload Reports
        uses: actions/upload-artifact@v7
        with:
          name: Reports
          path: ./**/build/reports
        if: always()
