# Workflow name
name: Build Release

# When it will be triggered
on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Where it will run
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-android
        with:
          signing-key: ${{ secrets.SIGNING_KEY }}
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_ALIAS: ${{ secrets.SIGNING_ALIAS }}

      - name: Create release build
        run: ./gradlew app:bundleRelease app:assembleRelease

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: Builds
          path: |
            app/build/outputs/apk/release/**/*.apk

  changelog:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          draft: false
          make_latest: true
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
          files: |
            **/*.apk
